module.exports = {
  homeHeading: 'h1',
  signupLoginLinkText: 'text=Signup/Login',
  signupPagePath: '/login',
  newUserSignupText: 'text=New User Signup!',
  namePlaceholder: 'input[placeholder="Name"]',
  nameFieldAlt: 'input[name="name"]',
  signupEmail: 'input[data-qa="signup-email"]',
  signupButton: 'button[data-qa="signup-button"]',
  accountInfoText: 'text=ENTER ACCOUNT INFORMATION',
  passwordInput: 'input[data-qa="password"]',
  daysSelect: 'select[data-qa="days"]',
  monthsSelect: 'select[data-qa="months"]',
  yearsSelect: 'select[data-qa="years"]',
  newsletterCheckbox: 'input#newsletter',
  optinCheckbox: 'input#optin',
  firstName: 'input[data-qa="first_name"]',
  lastName: 'input[data-qa="last_name"]',
  company: 'input[data-qa="company"]',
  address: 'input[data-qa="address"]',
  address2: 'input[data-qa="address2"]',
  countrySelect: 'select[data-qa="country"]',
  stateInput: 'input[data-qa="state"]',
  cityInput: 'input[data-qa="city"]',
  zipcodeInput: 'input[data-qa="zipcode"]',
  mobileInput: 'input[data-qa="mobile_number"]',
  createAccountButton: 'button[data-qa="create-account"]',
  accountCreatedText: 'text=ACCOUNT CREATED',
  continueButton: 'a[data-qa="continue-button"]',
  loggedInText: 'text=Logged in as',
  logoutLink: 'text=Logout',
  // login form selectors
  loginPageHeader: 'text=Login to your account',
  loginEmail: 'input[data-qa="login-email"]',
  loginPassword: 'input[data-qa="login-password"]',
  loginButton: 'button[data-qa="login-button"]',
  deleteHref: 'a[href*="delete"]',
  deleteTextXPath: '//a[contains(translate(text(), "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "abcdefghijklmnopqrstuvwxyz"), "delete")]',
  deleteHasText: 'a:has-text("Delete")',
  accountDeletedText: 'text=ACCOUNT DELETED'
};
