module.exports = {
  homeHeading: 'h1:first-of-type',
  signupLoginLinkText: 'text=Signup / Login',
  signupPagePath: '/login',
  newUserSignupText: 'text=New User Signup!',
  namePlaceholder: 'input[placeholder="Name"]',
  nameFieldAlt: 'input[name="name"]',
  signupEmail: 'input[data-qa="signup-email"]',
  signupButton: 'button[data-qa="signup-button"]',
  // flexible, case-insensitive match for duplicate-email messages (contains 'email' and 'exist')
  emailExistsError: 'xpath=//*[contains(translate(normalize-space(.), "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "abcdefghijklmnopqrstuvwxyz"), "email") and contains(translate(normalize-space(.), "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "abcdefghijklmnopqrstuvwxyz"), "exist")]',
  accountInfoText: 'text=ENTER ACCOUNT INFORMATION',
  passwordInput: 'input[data-qa="password"]',
  daysSelect: 'select[data-qa="days"]',
  monthsSelect: 'select[data-qa="months"]',
  yearsSelect: 'select[data-qa="years"]',
  newsletterCheckbox: 'input#newsletter',
  optinCheckbox: 'input#optin',
  firstName: 'input[data-qa="first_name"]',
  lastName: 'input[data-qa="last_name"]',
  company: 'input[data-qa="company"]',
  address: 'input[data-qa="address"]',
  address2: 'input[data-qa="address2"]',
  countrySelect: 'select[data-qa="country"]',
  stateInput: 'input[data-qa="state"]',
  cityInput: 'input[data-qa="city"]',
  zipcodeInput: 'input[data-qa="zipcode"]',
  mobileInput: 'input[data-qa="mobile_number"]',
  createAccountButton: 'button[data-qa="create-account"]',
  accountCreatedText: 'text=ACCOUNT CREATED',
  continueButton: 'a[data-qa="continue-button"]',
  loggedInText: 'text=Logged in as',
  logoutLink: 'text=Logout',
  // login form selectors
  loginPageHeader: 'text=Login to your account',
  loginEmail: 'input[data-qa="login-email"]',
  loginPassword: 'input[data-qa="login-password"]',
  loginButton: 'button[data-qa="login-button"]',
  loginErrorMessage: 'text=Your email or password is incorrect!',
  deleteHref: 'a[href*="delete"]',
  deleteTextXPath: '//a[contains(translate(text(), "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "abcdefghijklmnopqrstuvwxyz"), "delete")]',
  deleteHasText: 'a:has-text("Delete")',
  accountDeletedText: 'text=ACCOUNT DELETED',
  // Contact Us form selectors
  contactUsLink: 'a[href*="contact"]',
  contactUsText: 'text=Contact Us',
  getTouchHeading: 'text=GET IN TOUCH',
  contactNameInput: 'input[placeholder="Name"]',
  contactEmailInput: 'input[placeholder="Email"]',
  contactSubjectInput: 'input[placeholder="Subject"]',
  contactMessageTextarea: 'xpath=//textarea[@name="message"]',
  contactFileInput: 'input[name="upload_file"]',
  contactSubmitButton: 'input[type="submit"]',
  contactSuccessMessage: '.status.alert.alert-success',
  homeLink: 'a[href*="/"]',
  homeButton: 'text=Home',
  // new selectors for additional test cases
  testCasesLink: 'text=Test Cases',
  productsLink: 'a[href="/products"]',
  productsHeading: 'h2.title.text-center',
  // category selectors
  categoriesSection: '.left-sidebar .category-products',
  categoryWomen: 'a[href="#Women"]',
  // explicit href values avoid matching product names elsewhere
  categoryDress: 'a[href="/category_products/1"]',
  categoryMen: 'a[href="#Men"]',
  categoryMenSub: 'a[href="/category_products/3"]',
  categoryPageHeading: 'h2.title.text-center',
  // brand selectors
  brandsSection: '.brands_products',
  brandLink: '.brands_products .brands-name li a',
  // search selectors
  productSearchInput: '#search_product',
  productSearchButton: '#submit_search',
  searchedProductsHeading: 'div.features_items h2.title',
  firstProductViewButton: '.features_items .product-image-wrapper a:has-text("View Product")',
  firstProductAddToCart: '.features_items .product-image-wrapper a:has-text("Add to cart")',
  productNameDetail: 'div.product-information h2',
  // selectors use XPath to ensure text presence and avoid hidden elements
  productCategoryDetail: 'xpath=//div[contains(@class,"product-information")]//p[contains(translate(., "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "abcdefghijklmnopqrstuvwxyz"), "category")]',
  // price could be represented as currency or plain number; match any non-empty span inside product-info
  productPriceDetail: 'xpath=//div[contains(@class,"product-information")]//span[string-length(normalize-space(.)) > 0]',
  productAvailabilityDetail: 'xpath=//div[contains(@class,"product-information")]//p[contains(translate(., "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "abcdefghijklmnopqrstuvwxyz"), "availability")]',
  productConditionDetail: 'div.product-information p:has-text("Condition")',
  productBrandDetail: 'div.product-information p:has-text("Brand")',
  subscriptionHeading: 'h2:has-text("Subscription")',
  subscriptionInput: '#susbscribe_email',
  subscriptionButton: 'footer form.searchform button[type="submit"]',
  subscriptionSuccessMessage: 'div.alert-success.alert',
  cartLink: 'a[href="/view_cart"]',
  // cart rows selector: table is inside a div.cart_info, not the table itself
  cartTableRows: 'div.cart_info table tbody tr',
  cartQuantityInput: 'td.cart_quantity button',
  cartPriceCell: 'td.cart_price p',
  cartTotalCell: 'td.cart_total p',
  cartViewProductLink: 'a:has-text("View Product")',
  proceedToCheckoutButton: 'a:has-text("Proceed To Checkout")',
  registerLoginButton: 'a:has-text("Register / Login")',
  addressDetailsHeading: 'h2:has-text("Address Details")',
  reviewOrderHeading: 'h2:has-text("Review Your Order")',
  commentTextArea: 'textarea[name="message"]',
  placeOrderButton: 'a:has-text("Place Order")',
  // review submission selectors
  reviewTab: 'a[href="#reviews"]',
  reviewNameInput: '#name',
  reviewEmailInput: '#email',
  reviewTextInput: '#review',
  reviewSubmitButton: '#button-review',
  reviewSuccessMessage: '#review-section span',
  // recommended items
  recommendedItemsSection: '.recommended_items',
  recommendedAddToCart: '.recommended_items a.add-to-cart',
  // only attempt to add from the currently active carousel slide
  activeRecommendedAddToCart: '.recommended_items .item.active a.add-to-cart',
  recommendedViewCartButton: 'a:has-text("View Cart")',
  nameOnCardInput: 'input[name="name_on_card"]',
  nameOnCardInput: 'input[name="name_on_card"]',
  cardNumberInput: 'input[name="card_number"]',
  cvcInput: 'input[name="cvc"]',
  expiryMonthInput: 'input[name="expiry_month"]',
  expiryYearInput: 'input[name="expiry_year"]',
  payAndConfirmButton: 'button:has-text("Pay and Confirm Order")',
  orderPlacedMessage: 'p:has-text("Your order has been placed successfully!")',
  deleteAccountButton: 'a:has-text("Delete Account")',
  // new selectors for additional test cases
  deliveryAddress: '.address_delivery',
  billingAddress: '.address_billing',
  downloadInvoiceButton: 'a:has-text("Download Invoice")',
  scrollUpArrow: 'a#scrollUp',
  fullFledgedText: 'h2:has-text("Full-Fledged practice website for Automation Engineers")'};